# Generated by Django 4.1.7 on 2023-03-31 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='descrip',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='laptop',
            old_name='imagen',
            new_name='imagenes',
        ),
    ]
